# Generated by Django 5.1.2 on 2024-10-27 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinpartner', '0002_vehicles_bahan_bakar'),
        ('sewajual', '0002_remove_katalog_owner_katalog_bookmarked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='katalog',
            name='bookmarked_by',
        ),
        migrations.AddField(
            model_name='katalog',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='joinpartner.partner'),
        ),
    ]
