# Generated by Django 5.1.2 on 2024-10-27 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewajual', '0003_remove_katalog_bookmarked_by_katalog_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='katalog',
            name='owner',
        ),
        migrations.AddField(
            model_name='katalog',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_vehicles', to=settings.AUTH_USER_MODEL),
        ),
    ]
