# Generated by Django 5.1.2 on 2024-10-24 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sewajual', '0003_alter_vehicle_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={},
        ),
    ]
