# Generated by Django 5.1.2 on 2024-10-27 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sewajual', '0003_remove_katalog_bookmarked_by'),
        ('sewajual', '0004_remove_katalog_owner_katalog_bookmarked_by'),
    ]

    operations = [
    ]
