# Generated by Django 5.1.2 on 2024-10-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewajual', '0004_alter_vehicle_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='notelp',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='bahan_bakar',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='merk',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='warna',
            field=models.CharField(max_length=100),
        ),
    ]
