# Generated by Django 5.1.2 on 2024-10-24 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_vehicle_notelp'),
        ('sewajual', '0005_vehicle_notelp_alter_vehicle_bahan_bakar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Katalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vehicle')),
            ],
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
