# Generated by Django 5.1.2 on 2024-12-02 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joinpartner', '0003_delete_vehicles'),
        ('main', '0001_initial'),
        ('sewajual', '0006_katalog_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='katalog',
            unique_together={('vehicle', 'owner')},
        ),
    ]
