# Generated by Django 5.1.2 on 2024-10-26 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_vehicle_notelp'),
        ('sewajual', '0007_katalog_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalog',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='katalog_entries', to='main.vehicle'),
        ),
    ]
