# Generated by Django 5.1.2 on 2024-12-03 07:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinpartner', '0003_delete_vehicles'),
        ('sewajual', '0007_alter_katalog_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('toko', models.CharField(max_length=255)),
                ('merk', models.CharField(max_length=100)),
                ('tipe', models.CharField(max_length=100)),
                ('warna', models.CharField(max_length=100)),
                ('jenis_kendaraan', models.CharField(max_length=50)),
                ('harga', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('notelp', models.CharField(max_length=15, null=True)),
                ('bahan_bakar', models.CharField(max_length=50)),
                ('link_lokasi', models.URLField()),
                ('link_foto', models.URLField()),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='joinpartner.partner')),
            ],
        ),
        migrations.DeleteModel(
            name='Katalog',
        ),
    ]
