# Generated by Django 5.1.2 on 2024-10-26 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinpartner', '0002_partner_status_alter_vehicle_vehicle_image'),
        ('sewajual', '0008_alter_katalog_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalog',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='katalog_entries', to='joinpartner.partner'),
        ),
    ]
