# Generated by Django 5.1.2 on 2024-10-27 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinpartner', '0002_partner_status_alter_vehicle_vehicle_image'),
        ('main', '0002_vehicle_notelp'),
        ('sewajual', '0009_alter_katalog_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalog',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='joinpartner.partner'),
        ),
        migrations.AlterField(
            model_name='katalog',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vehicle'),
        ),
    ]
