# Generated by Django 5.1.2 on 2024-12-03 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
        ('sewajual', '0008_vehicle_delete_katalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='sewajual.vehicle'),
        ),
    ]
