# Generated by Django 5.1.2 on 2024-10-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_report_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='issue_type',
            field=models.CharField(choices=[('mismatch', 'Kendaraan tidak sesuai yang dipesan'), ('damaged', 'Kendaraan rusak'), ('service', 'Pelayanan tidak ramah')], max_length=10),
        ),
    ]
