# Generated by Django 5.1.2 on 2024-10-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_alter_report_issue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='issue_type',
            field=models.CharField(max_length=100),
        ),
    ]
