# Generated by Django 5.1.2 on 2024-10-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_report_issue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='issue_type',
            field=models.CharField(choices=[('Mismatch', 'Kendaraan tidak sesuai yang dipesan'), ('Damaged', 'Kendaraan rusak'), ('Service', 'Pelayanan tidak ramah')], max_length=10),
        ),
    ]
