# Generated by Django 5.1.4 on 2024-12-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentdriver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('minibus', 'Minibus')], max_length=50),
        ),
    ]
