# Generated by Django 5.1.2 on 2024-10-24 08:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('toko', models.CharField(max_length=255)),
                ('merk', models.CharField(max_length=100)),
                ('tipe', models.CharField(max_length=100)),
                ('warna', models.CharField(max_length=100)),
                ('jenis_kendaraan', models.CharField(max_length=50)),
                ('harga', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('bahan_bakar', models.CharField(max_length=50)),
                ('link_lokasi', models.URLField()),
                ('link_foto', models.URLField()),
            ],
        ),
    ]
