# Generated by Django 5.1.4 on 2024-12-20 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('sewajual', '0008_vehicle_delete_katalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sewajual.vehicle'),
        ),
    ]
