# Generated by Django 5.1.2 on 2024-10-27 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='helpful_votes',
        ),
    ]
