# Generated by Django 5.1.2 on 2024-10-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_reviews_description_alter_reviews_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='helpful_votes',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
