# Generated by Django 5.1.2 on 2024-10-27 03:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('toko', models.CharField(max_length=255)),
                ('link_lokasi', models.URLField(max_length=500)),
                ('notelp', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_foto', models.URLField(max_length=500)),
                ('merk', models.CharField(max_length=100)),
                ('tipe', models.CharField(max_length=100)),
                ('jenis_kendaraan', models.CharField(max_length=100)),
                ('warna', models.CharField(max_length=50)),
                ('harga', models.IntegerField()),
                ('status', models.CharField(choices=[('Sewa', 'Sewa'), ('Jual', 'Jual')], default='Sewa', max_length=15)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='joinpartner.partner')),
            ],
        ),
    ]
