# Generated by Django 5.1.2 on 2024-10-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinpartner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='bahan_bakar',
            field=models.CharField(default='Bensin', max_length=50),
        ),
    ]
