# Generated by Django 5.1.2 on 2024-11-25 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joinpartner', '0002_vehicles_bahan_bakar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicles',
        ),
    ]
