# Generated by Django 5.1.2 on 2024-10-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinpartner', '0002_partner_status_alter_vehicle_vehicle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Sewa', 'Sewa'), ('Jual', 'Jual')], max_length=15),
        ),
    ]
