# Generated by Django 5.1.2 on 2024-10-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinpartner', '0003_alter_vehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Sewa', 'Sewa'), ('Jual', 'Jual')], default='Sewa', max_length=15),
        ),
    ]
