# Generated by Django 5.1.2 on 2024-10-23 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joinpartner', '0004_alter_vehicle_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicle',
            new_name='Vehicles',
        ),
    ]
