# Generated by Django 5.1.1 on 2024-10-24 14:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinpartner', '0005_rename_vehicle_vehicles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
