# Generated by Django 5.1.2 on 2024-10-25 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joinpartner', '0007_alter_vehicles_price_per_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='gmaps_link',
            new_name='link_lokasi',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='phone_number',
            new_name='notelp',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='store_name',
            new_name='toko',
        ),
        migrations.RenameField(
            model_name='vehicles',
            old_name='price_per_day',
            new_name='harga',
        ),
        migrations.RenameField(
            model_name='vehicles',
            old_name='brand',
            new_name='jenis_kendaraan',
        ),
        migrations.RenameField(
            model_name='vehicles',
            old_name='vehicle_image',
            new_name='link_foto',
        ),
        migrations.RenameField(
            model_name='vehicles',
            old_name='brand_type',
            new_name='merk',
        ),
        migrations.RenameField(
            model_name='vehicles',
            old_name='vehicle_type',
            new_name='tipe',
        ),
        migrations.RenameField(
            model_name='vehicles',
            old_name='color',
            new_name='warna',
        ),
    ]
